# Graphen

#### 1. Route zwischen zwei Knoten

>   a) 
    Implementieren Sie einen Algorithmus, der in einem gerichteten Graphen (gegeben durch Adjazenzliste) bestimmt, ob es zwischen zwei Knoten eine Route gibt, oder nicht. Die Prozedur soll entsprechend einen Boolean zurückgeben, der dies angibt.
    
>   b) 
    Bestimmen Sie die Laufzeit Ihres Algorithmus.
    
#### 2. Erreichbare Knoten

>   a) 
    Schreiben Sie eine Prozedur, die einen Knoten $v$ als Parameter nimmt und die Menge an Knoten zurückgibt, die von dem Knoten $v$ aus erreichbar sind.
    
>   b) 
    Bestimmen Sie die Laufzeit Ihres Algorithmus.
   
#### 3. Sudoku

>   a) 
    Implementieren Sie einen Algorithmus, der ein beliebiges $n \times n$ Sudoku mit $\sqrt{n} \in \mathbb{N}$ löst. Es gelten dabei folgende Regeln:
    
>   - Nur die Zahlen 1 bis $n$ kommen vor.
>   - In jeder Ziele kommt eine Zahl genau einmal vor.
>   - In jeder Spalte kommt eine Zahl genau einmal vor.
>   - In jedem $\sqrt{n} \times \sqrt{n}$-Quadrat kommt eine Zahl genau einmal vor.
   
>   Verwenden Sie dabei ein 2-dimensionales Array als Datenstruktur. Beachten Sie, dass wie beim richtigen Sudoku einige Felder bereits ausgefüllt sein können.

>   b) 
    Bestimmen Sie die Laufzeit Ihres Algorithmus.

1.

In [10]:
import doctest

class Node:
    def __init__(self, name):
        self.name = name
        self.adj = []
        
    def add_to_adj_lst(self, node):
        self.adj.append(node)

a = Node('A')
b = Node('B')
c = Node('C')
d = Node('D')
e = Node('E')
f = Node('F')
g = Node('G')

a.add_to_adj_lst(b)
b.add_to_adj_lst(c)
b.add_to_adj_lst(e)
b.add_to_adj_lst(d)
c.add_to_adj_lst(e)
d.add_to_adj_lst(e)
e.add_to_adj_lst(f)
g.add_to_adj_lst(d)


def adjacent(a, b, visited=set()):
    """
    >>> adjacent(a, b)
    True
    
    >>> adjacent(a, g)
    False
    
    >>> adjacent(a, d)
    True
    
    >>> adjacent(a, e)
    True
    """
    # your code goes here, implement the method to make the test cases pass
    
    
    
doctest.run_docstring_examples(adjacent, globals())

**********************************************************************
File "__main__", line 31, in NoName
Failed example:
    adjacent(a, b)
Expected:
    True
Got nothing
**********************************************************************
File "__main__", line 34, in NoName
Failed example:
    adjacent(a, g)
Expected:
    False
Got nothing
**********************************************************************
File "__main__", line 37, in NoName
Failed example:
    adjacent(a, d)
Expected:
    True
Got nothing
**********************************************************************
File "__main__", line 40, in NoName
Failed example:
    adjacent(a, e)
Expected:
    True
Got nothing


2.

In [11]:
def reachable_nodes(root, visited=set()):
    """
    >>> len(reachable_nodes(a))
    6
    
    >>> len(reachable_nodes(b))
    5
    
    >>> len(reachable_nodes(d))
    3
    
    >>> len(reachable_nodes(f))
    1
    
    >>> len(reachable_nodes(g))
    4
    """
    # your code goes here, implement the method to make the test cases pass

    
doctest.run_docstring_examples(reachable_nodes, globals())

**********************************************************************
File "__main__", line 3, in NoName
Failed example:
    len(reachable_nodes(a))
Exception raised:
    Traceback (most recent call last):
      File "C:\Users\Administrator\Anaconda3\lib\doctest.py", line 1330, in __run
        compileflags, 1), test.globs)
      File "<doctest NoName[0]>", line 1, in <module>
        len(reachable_nodes(a))
    TypeError: object of type 'NoneType' has no len()
**********************************************************************
File "__main__", line 6, in NoName
Failed example:
    len(reachable_nodes(b))
Exception raised:
    Traceback (most recent call last):
      File "C:\Users\Administrator\Anaconda3\lib\doctest.py", line 1330, in __run
        compileflags, 1), test.globs)
      File "<doctest NoName[1]>", line 1, in <module>
        len(reachable_nodes(b))
    TypeError: object of type 'NoneType' has no len()
******************************************************************

3.

In [12]:
import numpy as np # you should use numpy matrices for this task

def solve_sudoku(sudoku, n=None):
    """
    >>> solve_sudoku(np.matrix([[0,9,0,8,0,0,0,5,7],[0,0,6,0,0,1,0,2,0],[3,0,0,0,7,0,0,0,0],[5,0,0,9,0,6,0,3,8],[0,3,0,0,1,0,0,0,0],[2,0,8,0,0,0,5,1,0],[6,0,0,0,9,0,0,0,3],[0,1,0,0,0,0,0,9,0],[0,0,7,6,0,5,8,0,0]]))
    matrix([[1, 9, 4, 8, 6, 2, 3, 5, 7],
            [8, 7, 6, 3, 5, 1, 9, 2, 4],
            [3, 5, 2, 4, 7, 9, 1, 8, 6],
            [5, 4, 1, 9, 2, 6, 7, 3, 8],
            [7, 3, 9, 5, 1, 8, 4, 6, 2],
            [2, 6, 8, 7, 4, 3, 5, 1, 9],
            [6, 8, 5, 1, 9, 4, 2, 7, 3],
            [4, 1, 3, 2, 8, 7, 6, 9, 5],
            [9, 2, 7, 6, 3, 5, 8, 4, 1]])
    >>> solve_sudoku(np.matrix([[4,0,2,9,0,5,8,0,3],[3,9,0,0,0,0,0,6,4],[0,0,1,0,0,0,9,0,0],[0,0,0,5,0,1,0,0,0],[0,4,0,6,0,2,0,3,0],[0,0,0,4,0,8,0,0,0],[0,0,7,0,0,0,5,0,0],[5,1,0,0,0,0,0,2,7],[9,0,4,7,0,3,6,0,8]]))
    matrix([[4, 6, 2, 9, 1, 5, 8, 7, 3],
            [3, 9, 5, 2, 8, 7, 1, 6, 4],
            [7, 8, 1, 3, 6, 4, 9, 5, 2],
            [2, 7, 9, 5, 3, 1, 4, 8, 6],
            [1, 4, 8, 6, 9, 2, 7, 3, 5],
            [6, 5, 3, 4, 7, 8, 2, 9, 1],
            [8, 3, 7, 1, 2, 6, 5, 4, 9],
            [5, 1, 6, 8, 4, 9, 3, 2, 7],
            [9, 2, 4, 7, 5, 3, 6, 1, 8]])
    """
    # your code goes here, implement the method to make the test cases pass
    
    
doctest.run_docstring_examples(solve_sudoku, globals())

**********************************************************************
File "__main__", line 5, in NoName
Failed example:
    solve_sudoku(np.matrix([[0,9,0,8,0,0,0,5,7],[0,0,6,0,0,1,0,2,0],[3,0,0,0,7,0,0,0,0],[5,0,0,9,0,6,0,3,8],[0,3,0,0,1,0,0,0,0],[2,0,8,0,0,0,5,1,0],[6,0,0,0,9,0,0,0,3],[0,1,0,0,0,0,0,9,0],[0,0,7,6,0,5,8,0,0]]))
Expected:
    matrix([[1, 9, 4, 8, 6, 2, 3, 5, 7],
            [8, 7, 6, 3, 5, 1, 9, 2, 4],
            [3, 5, 2, 4, 7, 9, 1, 8, 6],
            [5, 4, 1, 9, 2, 6, 7, 3, 8],
            [7, 3, 9, 5, 1, 8, 4, 6, 2],
            [2, 6, 8, 7, 4, 3, 5, 1, 9],
            [6, 8, 5, 1, 9, 4, 2, 7, 3],
            [4, 1, 3, 2, 8, 7, 6, 9, 5],
            [9, 2, 7, 6, 3, 5, 8, 4, 1]])
Got nothing
**********************************************************************
File "__main__", line 15, in NoName
Failed example:
    solve_sudoku(np.matrix([[4,0,2,9,0,5,8,0,3],[3,9,0,0,0,0,0,6,4],[0,0,1,0,0,0,9,0,0],[0,0,0,5,0,1,0,0,0],[0,4,0,6,0,2,0,3,0],[0,0,0,4,0,8,0,0,0],[0,0